image: node:latest

cache:
    paths:
        - node_modules/

stages:
    - build
    - deploy

variables:
    REACT_APP_BOOKING_URL: $BOOKING_URL

build:
    stage: build
    variables:
        REACT_APP_BOOKING_URL: "build"
    script:
        - yarn
        - yarn build
    only:
        - master
    artifacts:
        paths:
            - build

deploy:
    stage: deploy
    variables:
        REACT_APP_BOOKING_URL: "deploy"
    script:
        - ls -al
        - mkdir -p ~/.ssh
        - cat $SSH_PRIVATE_KEY > ~/.ssh/gitlab
        - chmod 700 ~/.ssh/gitlab
        - scp -i ~/.ssh/gitlab -o StrictHostKeyChecking=no -rC ./build/* front@85.193.90.205:/home/front/www/lk.dknord.ru/
    only:
        - master
