image: node:latest

cache:
    paths:
        - node_modules/

stages:
    - build
    - deploy

build:
    stage: build
    script:
        - yarn
        - yarn build
    only:
        - master
    artifacts:
        paths:
            - build

deploy:
    stage: deploy
    script:
        - ls -al
        - mkdir -p ~/.ssh
        - cat $SSH_PRIVATE_KEY
        - echo $SSH_PRIVATE_KEY > ~/.ssh/gitlab
        - chmod 700 ~/.ssh/gitlab
        - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
        - cat ~/.ssh/gitlab
        - cat ~/.ssh/known_hosts
        - scp -i ~/.ssh/gitlab -o StrictHostKeyChecking=no -rC ./build/* frontend@85.193.90.205:/home/frontend/material-acc-prod/
    only:
        - master
