image: node:latest

cache:
    paths:
        - node_modules/

stages:
    - build
    - deploy

build:
    stage: build
    script:
        - yarn
        - yarn build
    only:
        - master
    artifacts:
        paths:
            - build

deploy:
    stage: deploy
    script:
        - ls -al
    only:
        - master
